### ISSUE TITLE
hwlatdetect and cyclictest needs access to `/dev/cpu_dma_latency`

### ISSUE THREAD

**Issue by locnnil** [canonical/rt-tests-snap#21]
An udev rule is missing for `/dev/cpu_dma_latency`

```bash
sudo hwlatdetect --duration 5s
hwlatdetect:  test duration 5 seconds
   detector: tracer
   parameters:
        CPU list:          None
        Latency threshold: 10us
        Sample window:      1000000us
        Sample width:      500000us
     Non-sampling period:  500000us
        Output File:       None

Starting test
Traceback (most recent call last):
  File "/snap/rt-tests/x1/usr/sbin/hwlatdetect", line 509, in <module>
    detect.detect()
  File "/snap/rt-tests/x1/usr/sbin/hwlatdetect", line 297, in detect
    self.start()
  File "/snap/rt-tests/x1/usr/sbin/hwlatdetect", line 194, in start
    self.c_states_off()
  File "/snap/rt-tests/x1/usr/sbin/hwlatdetect", line 160, in c_states_off
    self.dma_latency_handle = os.open("/dev/cpu_dma_latency", os.O_WRONLY)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/dev/cpu_dma_latency'

```

**Comment by farshidtz** [comment]
Closed via #20

**Comment by farshidtz** [comment]
Reopening as the fix hasn't been merged into main.

**Comment by farshidtz** [comment]
There is also a warning for this when using cyclictests:
```
WARN: open /dev/cpu_dma_latency: Operation not permitted
```

When installed in dev mode to allow access:
```
#/dev/cpu_dma_latency set to 0us
```

**Comment by farshidtz** [comment]
Should soon be made accessible via the [cpu-control](https://snapcraft.io/docs/cpu-control-interface) interface: 
- https://github.com/snapcore/snapd/pull/14154
